### ISSUE TITLE
Catapults

### ISSUE THREAD

**Issue by srichardson001** [TWOverflow/TWOverflow#56]
When you schedule catapults it will always attack headquarters no matter which option you pick from twoverflow.

**Comment by mafrazz** [comment]
Thank! Testing...

**Comment by mafrazz** [comment]
Thanks! Testing...

**Comment by srichardson001** [comment]
Any chance you could take another look at this?

**Comment by mafrazz** [comment]
Fixed on update 1.0.2, tell me if the problem persist.
