### ISSUE TITLE
No map refresh

### ISSUE THREAD

**Issue by nixniax** [TWOverflow/TWOverflow#58]
No map refresh.  Bot attacks players who occupy barbarian villages. You can easly get banned for that

**Comment by q2111872** [comment]
Agreed, this is a problem :/

**Comment by mafrazz** [comment]
I gonna check this.

**Comment by srichardson001** [comment]
This is problem in the game client.  Unless you refresh your browser the city will show barbarian after it has been taken by another player.

**Comment by srichardson001** [comment]
The only work around I can think of if having the script reload the page after X minutes.  But, then there will need to be a way to re-enable the script after a reload.

**Comment by mafrazz** [comment]
I managed to work around this problem, will be in next update.
