### ISSUE TITLE
Script attacks all the time same villages

### ISSUE THREAD

**Issue by q2111872** [TWOverflow/TWOverflow#59]
If there is few hundred attacks sent, script is starting to attack same village in the same time (for example atack every 2 min). 
Even if distance is set min - 0, max - 50, and max time 04:00:00 its happening all the time.
In my opinion it should spread more and more, to not duplicate attacks.

**Comment by mafrazz** [comment]
The script's attacking all targets that it's supposed to attack? Or it is avoiding some villages?
