### ISSUE TITLE
AttackView, BRAVO !!! 

### ISSUE THREAD

**Issue by starlord51** [TWOverflow/TWOverflow#66]
I have to complement you for adding AttackView, BEST FEATURES EVER :100: =D

Suggestion:
- Options to automatic "set a CommandQueue to remove all troops before attack hit"

Bugs found:
- Copy backtime date is not working property

**Comment by mafrazz** [comment]
Thanks.
About the backtime date, the copied date is incorrect?

**Comment by starlord51** [comment]
The backtime date, this is what copied:

19:29:28 01/01/1970

**Comment by starlord51** [comment]
![screenshot_2](https://user-images.githubusercontent.com/37132489/41205586-c4ebf8ae-6d28-11e8-8ca3-40e1f3c7f477.jpg)

There is this bug now, look at the traveling time...

**Comment by mafrazz** [comment]
Thank you

**Comment by starlord51** [comment]
and also, in this bug... in the "SU" field, it's not showing the correct unit type for the incoming...

i just used my A01 village to sent 1 LC to my A02 village
in "SU", it showed AXE MAN with that bug traveling time

**Comment by mafrazz** [comment]
Fixed

**Comment by starlord51** [comment]
In the "SU" field, it's not showing the right unit... I just sent myself an ATTACK using LC, its show incoming axeman... but the traveling time is correct

**Comment by mafrazz** [comment]
Thank you, the order between axe man and LC/MA was inverted.
Fixed.

**Comment by starlord51** [comment]
kudos to you... Good job for doing all this =) and thank you for providing such a wonderful script
